import { createRequire } from 'node:module';
import { existsSync, mkdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
const { chromium } = createRequire(import.meta.url)('C:/Users/Asus/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base = process.env.ACCEPTANCE_URL || 'https://gaygay-lab.github.io/determinant-lab/';
const stamp = process.env.ACCEPTANCE_COMMIT || Date.now();
const url = `${base}${base.includes('?')?'&':'?'}v=${stamp}`;
const browser = await chromium.launch({headless:true, executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const out=[]; const pass=(id,d)=>out.push(`PASS ${id} ${d}`), fail=(id,d)=>out.push(`FAIL ${id} ${d}`);
async function fresh(viewport={width:1440,height:900},init=true){const context=await browser.newContext({viewport});if(init)await context.addInitScript(()=>{sessionStorage.setItem('det-lab-opening-v3','seen');sessionStorage.setItem('det-lab-tutorial-v3','seen')});const page=await context.newPage();page.on('pageerror',e=>console.error('pageerror',e.message));await page.goto(url,{waitUntil:'networkidle'});await page.waitForTimeout(180);return {context,page};}
async function skip(page){if(await page.locator('#openingDemo').isVisible().catch(()=>false))await page.locator('#openingSkip').click();if(await page.locator('#tutorialOverlay').isVisible().catch(()=>false))await page.locator('#tutorialSkip').click();}
async function openBank(page){if(await page.locator('#bankMenu').isHidden())await page.locator('#bankToggle').click();}
async function choose(page,index){await openBank(page);await page.locator('#problemList .problem-link').nth(index).click();await page.waitForTimeout(60);}
async function solveFirst(page){await page.locator('#apply').click();await page.locator('#readResult').click();await page.locator('#answerInput').fill('-2');await page.locator('#answerSubmit').click();}
// C1: a genuinely visible opening board runs an animation.
{const {context,page}=await fresh({width:1440,height:900},false);const visible=await page.locator('#openingDemo').isVisible();const initial=await page.evaluate(()=>document.getAnimations().length);await page.waitForTimeout(260);const running=await page.evaluate(()=>document.getAnimations().length);const board=await page.locator('#openingMatrix .play-cell').count();if(visible&&board===9&&running>0)pass('C1',`opening board=${board}; animations before/after=${initial}/${running}`);else fail('C1',`visible=${visible}; board=${board}; animations=${initial}/${running}`);await page.locator('#openingSkip').click();await context.close();}
// C2: wrong clicks are ignored; each correct action moves one spotlight.
{const {context,page}=await fresh({width:1440,height:900},false);await page.locator('#openingSkip').click();let steps=[];steps.push(await page.locator('#tutorialOverlay').getAttribute('data-step'));await page.locator('#tutorialNext').click();steps.push(await page.locator('#tutorialOverlay').getAttribute('data-step'));await page.locator('[data-tour-step="3"]').click();const wrong=await page.locator('#tutorialOverlay').getAttribute('data-step');await page.locator('[data-tour-step="2"]').click();steps.push(await page.locator('#tutorialOverlay').getAttribute('data-step'));await page.locator('[data-tour-step="2"]').count();await page.locator('[data-tour-step="3"]').click({button:'right'});steps.push(await page.locator('#tutorialOverlay').getAttribute('data-step'));await page.locator('#apply').click();steps.push(await page.locator('#tutorialOverlay').getAttribute('data-step'));await page.locator('#zeroCount').click();steps.push(await page.locator('#tutorialOverlay').getAttribute('data-step'));const roots=await page.evaluate(()=>[1,2,3,4,5,6].map(i=>document.querySelectorAll(`[data-tour-step="${i}"]`).length));if(steps.join(',')==='1,2,3,4,5,6'&&wrong==='2'&&roots.every(Boolean))pass('C2',`sequence=${steps.join('→')}; wrong stayed ${wrong}; roots=${roots.join('/')}`);else fail('C2',`sequence=${steps.join('→')}; wrong=${wrong}; roots=${roots.join('/')}`);await context.close();}
// C3/C4/C6: one entry; every replay has a real animation and engine-equivalent answer.
{const {context,page}=await fresh();await skip(page);const demoCount=await page.locator('#demoButton').count();const oldCount=await page.locator('#showDemo, .guide-link, .demo-route-button').count();const hints=await page.locator('.key-strip').innerText();const ops=await page.locator('[data-op]').allTextContents();if(demoCount===1&&oldCount===0)pass('C3','one #demoButton and no duplicate demo entries');else fail('C3',`demo=${demoCount}; old=${oldCount}`);if(hints.includes('T')&&hints.includes('V')&&ops.some(x=>x.includes('交换')&&x.includes('S'))&&ops.some(x=>x.includes('转置')&&x.includes('T')))pass('C6','T=转置, V=重置, S=交换 labels agree');else fail('C6',`hints=${hints}`);
 await openBank(page);const total=await page.locator('#problemList .problem-link').count();let bad=[];for(let i=0;i<total;i++){await page.locator('#problemList .problem-link').nth(i).click();await page.waitForTimeout(25);await page.locator('#demoButton').click();await page.locator('#demoSpeed').selectOption('4');let animated=false;try{await page.waitForFunction(()=>document.getAnimations().length>0,{timeout:1300});animated=true}catch{}let answer='';try{await page.waitForFunction(()=>!!document.getElementById('demoFormula')?.dataset.answer,{timeout:7000});answer=await page.locator('#demoFormula').getAttribute('data-answer');}catch{}const id=await page.locator('#problemList .problem-link.current').getAttribute('data-problem');const equal=await page.evaluate(({id,answer})=>{try{const p=window.PROBLEMS.find(x=>x.id===Number(id));return !!p&&!!answer&&(answer===window.SymbolicGame.format(p.expected)||window.SymbolicGame.equals(window.SymbolicGame.polynomial(String(answer).replaceAll('−','-').replaceAll('＋','+')),p.expected))}catch{return false}},{id,answer});if(!animated||!equal)bad.push(`${id||i+1}:animated=${animated},answer=${answer}`);await page.locator('#demoClose').click();}if(total>=70&&bad.length===0)pass('C4',`${total} demos: animation and engine answer verified`);else fail('C4',`total=${total}; bad=${bad.slice(0,8).join('|')}`);await context.close();}
// C5: exact in-page leave copy and once/session behavior.
{const {context,page}=await fresh();await page.locator('#apply').click();await page.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseout',{bubbles:true,clientY:0,relatedTarget:null})));const text=await page.locator('#exitMessage').innerText().catch(()=>''),shown=await page.locator('#exitModal').isVisible();await page.locator('#exitContinue').click();await page.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseout',{bubbles:true,clientY:0,relatedTarget:null})));const again=await page.locator('#exitModal').isVisible();const exact='不好玩吗？还是做题更方便，那么帮助到你学习行列式了，这就已经完成了此游戏的使命了~';if(shown&&text===exact&&!again)pass('C5','exact copy and one prompt per session');else fail('C5',`shown=${shown}; exact=${text===exact}; again=${again}`);await context.close();}
// C7/C8/C9/C11: special mathematics and executable modes.
{const {context,page}=await fresh();const special=await page.evaluate(()=>window.PROBLEMS.filter(p=>p.special==='cos-tridiagonal').map(p=>p.n));const numeric=await page.evaluate(()=>window.PROBLEMS.filter(p=>p.special==='cos-tridiagonal').every(p=>{const q=window.SymbolicGame.cosTridiagonal(p.n);return [0.13,0.37,0.81].every(c=>{const th=Math.acos(c),want=Math.sin((p.n+1)*th)/Math.sin(th),v=window.SymbolicGame.evaluate(q.polynomial,c);return Math.abs(Number(v.n)/Number(v.d)-want)<1e-8})}));if(special.length>=3&&numeric)pass('C7',`n=${special.join(',')} and 3 random cos values agree with closed form`);else fail('C7',`n=${special}; numeric=${numeric}`);await openBank(page);const meng=page.locator('#problemList .problem-link').filter({hasText:'范德蒙'}).first();if(await meng.count()){await meng.click();const badge=await page.locator('.meng-badge').isVisible();if(badge)pass('C8','Vandermonde level shows 蒙 badge');else fail('C8','badge hidden');}else fail('C8','no Vandermonde level');await choose(page,0);await page.locator('[data-op="laplace"]').click();await page.locator('#apply').click();const lap=await page.locator('.math-special-panel[data-special="laplace"] .laplace-term').count();await page.locator('#definitionMode').click();const defOpen=await page.locator('#infoDialog').isVisible();let guard=0;while(defOpen&&guard++<8){const enabled=page.locator('[data-definition-cell]:not([disabled])');if(await enabled.count()===0)break;await enabled.first().click();}const closed=await page.locator('#definitionRoute').innerText().catch(()=>''),defDone=closed.includes('路线已闭合');if(lap>0&&defOpen&&defDone)pass('C9',`Laplace terms=${lap}; definition route closed`);else fail('C9',`laplace=${lap}; dialog=${defOpen}; route=${closed}`);const fun=await page.evaluate(()=>window.PROBLEMS.filter(p=>p.family==='爽关').length),all=await page.evaluate(()=>window.PROBLEMS.length);const readme=readFileSync('README.md','utf8');if(fun>=5&&all>=75&&readme.includes(`${all} 题`))pass('C11',`levels=${all}; 爽关=${fun}; README count agrees`);else fail('C11',`levels=${all}; fun=${fun}`);await context.close();}
// C10: mobile first win with taps and on-screen answer pad.
{const {context,page}=await fresh({width:390,height:844});await page.locator('#apply').click();await page.locator('#readResult').click();await page.locator('#answerPad [data-answer-key="−"]').click();await page.locator('#answerPad [data-answer-key="2"]').click();await page.locator('#answerSubmit').click();await page.waitForTimeout(1500);const title=await page.locator('#problemTitle').innerText();if(title.startsWith('02'))pass('C10','390×844 first level completed through taps and keypad');else fail('C10',`title=${title}`);await context.close();}
// C12: PNG is a real non-empty download.
{const {context,page}=await fresh();await page.locator('#apply').click();await page.locator('#readResult').click();await page.locator('#answerInput').fill('-2');await page.locator('#answerSubmit').click();const waitDownload=page.waitForEvent('download',{timeout:3000}).catch(()=>null);await page.locator('#saveMoment').click();const download=await waitDownload;if(download){const path=await download.path();if(path&&existsSync(path)&&statSync(path).size>64&&download.suggestedFilename().endsWith('.png'))pass('C12',`PNG download is non-empty (${statSync(path).size} bytes)`);else fail('C12','download empty or not PNG');}else fail('C12','no PNG download');await context.close();}
// C13 visual regression: compare screenshots with a before capture, excluding white pixels.
{const {context,page}=await fresh();const after='audit/after-home.png';await page.screenshot({path:after,fullPage:false});await context.close();const before=existsSync('audit/before/desktop-home.png')?'audit/before/desktop-home.png':'audit/before/desktop-level-1-page.png';const py=spawnSync('python',['-c',`from PIL import Image\nimport colorsys,sys\ndef f(p):\n im=Image.open(p).convert('RGB'); vals=[]\n for r,g,b in im.getdata():\n  if (r,g,b)!=(255,255,255) and min(r,g,b)<248: vals.append(colorsys.rgb_to_hsv(r/255,g/255,b/255)[1])\n return sum(vals)/len(vals) if vals else 0\na=f(sys.argv[1]);b=f(sys.argv[2]);print(f'{a:.6f} {b:.6f}')\nif a>0.15 or b>0.15: raise SystemExit(1)`,before,after],{encoding:'utf8'});if(py.status===0)pass('C13',`paper average saturation before/after=${(py.stdout||'').trim()}`);else fail('C13',`saturation check failed: ${(py.stdout||py.stderr||'').trim()}`);}
const tests=['tests/engine-test.cjs','tests/symbolic-test.cjs','tests/bank-test.cjs','tests/special-test.cjs'];const testResults=tests.map(f=>{const r=spawnSync('node',[f],{encoding:'utf8'});return {f,ok:r.status===0,out:(r.stdout||r.stderr||'').trim()};});if(testResults.every(x=>x.ok))pass('C14',testResults.map(x=>x.out).join(' | '));else fail('C14',JSON.stringify(testResults));
const report=out.join('\n')+'\n';mkdirSync('audit',{recursive:true});writeFileSync('audit/ACCEPTANCE.txt',report);console.log(report);await browser.close();if(out.some(x=>x.startsWith('FAIL')))process.exitCode=1;
