import { createRequire } from "node:module";
const { chromium } = createRequire(import.meta.url)("C:/Users/Asus/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright");
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";

const commit = process.env.ACCEPTANCE_COMMIT || "HEAD";
const url = `https://gaygay-lab.github.io/determinant-lab/?v=${commit}`;
const browser = await chromium.launch({headless:true, executablePath:"C:/Program Files/Google/Chrome/Application/chrome.exe"});
const results=[];
const pass=(id,detail)=>results.push({id,ok:true,detail});
const fail=(id,detail)=>results.push({id,ok:false,detail});
async function fresh(viewport={width:1440,height:900}){const ctx=await browser.newContext({viewport});const page=await ctx.newPage();await page.goto(url,{waitUntil:"networkidle"});return {ctx,page};}
async function dismissIntro(page){if(await page.locator('#openingSkip').isVisible().catch(()=>false)) await page.locator('#openingSkip').click();if(await page.locator('#tutorialSkip').isVisible().catch(()=>false)) await page.locator('#tutorialSkip').click();}
async function choose(page,level){await page.locator('#bankToggle').click().catch(()=>{});await page.locator('#problemList .problem-link').nth(level-1).click();await page.waitForTimeout(100);}
async function waitDemo(page){for(let i=0;i<90;i++){const t=await page.locator('#demoStepLabel').innerText();if(t.includes('演示完成'))return true;await page.waitForTimeout(200);}return false;}

// C1/C2 fresh first visit
{const {ctx,page}=await fresh();const visible=await page.locator('#openingDemo').isVisible();const animations=await page.evaluate(()=>document.getElementById('openingDemo')?.getAnimations().length||0);if(visible&&animations>0)pass('C1',`openingDemo visible; animations=${animations}`);else fail('C1',`visible=${visible}; animations=${animations}`);await page.locator('#openingSkip').click();const attrs=await page.locator('[data-tour-step]').all();const values=[];for(const l of attrs)values.push(await l.getAttribute('data-tour-step'));const unique=new Set(values.filter(Boolean));await page.locator('#tutorialNext').click();const locked=await page.locator('#tutorialNext').isDisabled();if(unique.size>=6&&locked)pass('C2',`data-tour-step values=${[...unique].join(',')}; step 2 waits for player`);else fail('C2',`values=${[...unique].join(',')}; locked=${locked}`);await ctx.close();}

// C3, C4 and C6 desktop
{const {ctx,page}=await fresh();await dismissIntro(page);const demos=await page.locator('#demoButton').count();const old=await page.locator('#showDemo').count();if(demos===1&&old===0)pass('C3','one demo entry: #demoButton');else fail('C3',`demoButton=${demos}; showDemo=${old}`);const hints=await page.locator('.key-strip').innerText();const labels=await page.locator('[data-op]').allTextContents();if(hints.includes('T')&&hints.includes('V')&&labels.some(x=>x.includes('S')))pass('C6','keyboard hints and action labels visible');else fail('C6','keyboard hint mismatch');
await page.locator('#bankToggle').click();const total=await page.locator('#problemList .problem-link').count();let bad=0;for(let i=0;i<total;i++){await page.locator('#problemList .problem-link').nth(i).click();await page.locator('#demoButton').click();if(!(await waitDemo(page)))bad++;await page.locator('#demoClose').click();}if(total>=70&&bad===0)pass('C4',`${total} level demos completed with answer state`);else fail('C4',`total=${total}; unfinished=${bad}`);await ctx.close();}

// C5 leave prompt after one move
{const {ctx,page}=await fresh();await dismissIntro(page);await page.locator('#axis').selectOption('row');await page.locator('#target').selectOption('1');await page.locator('#source').selectOption('0');await page.locator('#coefficient').fill('-3');await page.locator('#apply').click();await page.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseout',{bubbles:true,clientY:0,relatedTarget:null})));const shown=await page.locator('#exitModal').isVisible();if(shown)pass('C5','exitModal visible after progress and top mouseout');else fail('C5','exitModal not visible');await page.locator('#exitContinue').click();await page.evaluate(()=>document.dispatchEvent(new MouseEvent('mouseout',{bubbles:true,clientY:0,relatedTarget:null})));if(!(await page.locator('#exitModal').isVisible()))pass('C5-repeat','exitModal only once per session');else fail('C5-repeat','exitModal repeated');await ctx.close();}

// C7/C8/C9/C11 static+UI checks
{const {ctx,page}=await fresh();await dismissIntro(page);const stats=await page.evaluate(()=>({cos:(window.PROBLEMS||[]).filter(p=>p.special==='cos-tridiagonal').length,formula:(window.PROBLEMS||[]).filter(p=>p.special==='cos-tridiagonal').every(p=>String(p.formula||'').includes('sin')),fun:(window.PROBLEMS||[]).filter(p=>p.family==='爽关').length,total:(window.PROBLEMS||[]).length}));if(stats.cos>=3&&stats.formula)pass('C7',`cos-tridiagonal=${stats.cos}; formula fields present`);else fail('C7',JSON.stringify(stats));if(stats.fun>=5&&stats.total>=75)pass('C11',`total=${stats.total}; fun levels=${stats.fun}`);else fail('C11',JSON.stringify(stats));const meng=await page.locator('#problemList .problem-link').filter({hasText:'范德蒙'}).first();await page.locator('#bankToggle').click();if(await meng.count()){await meng.click();await page.waitForTimeout(120);if(await page.locator('#mengBadge').isVisible())pass('C8','meng-badge appears for Vandermonde');else fail('C8','meng-badge hidden');}else fail('C8','no Vandermonde level');if(await page.locator('[data-op="laplace"]').count()&&await page.locator('[data-mode="definition"]').count())pass('C9','laplace operation and definition mode present');else fail('C9','missing operation or mode');await ctx.close();}

// C10 mobile tap-only first level
{const {ctx,page}=await fresh({width:390,height:844});await dismissIntro(page);await page.locator('#axis').selectOption('row');await page.locator('#target').selectOption('1');await page.locator('#source').selectOption('0');await page.locator('#coefficient').fill('-3');await page.locator('#apply').click();await page.locator('#readResult').click();await page.locator('#answerInput').fill('-2');await page.locator('#answerSubmit').click();await page.waitForTimeout(1500);const title=await page.locator('#problemTitle').innerText();if(title.includes('02'))pass('C10','mobile tap-only first level completed');else fail('C10',title);await ctx.close();}

// C12 and C13 desktop screenshot/download after a solved state
{const {ctx,page}=await fresh();await dismissIntro(page);await page.locator('#axis').selectOption('row');await page.locator('#target').selectOption('1');await page.locator('#source').selectOption('0');await page.locator('#coefficient').fill('-3');await page.locator('#apply').click();await page.locator('#readResult').click();await page.locator('#answerInput').fill('-2');await page.locator('#answerSubmit').click();const dl=page.waitForEvent('download',{timeout:5000}).catch(()=>null);await page.locator('#saveMoment').click().catch(()=>{});const got=await dl;if(got)pass('C12','saveMoment produced a download');else fail('C12','PNG download missing');const colors=await page.evaluate(()=>{const nodes=[document.body,document.querySelector('.play-matrix'),document.querySelector('.topbar')];return nodes.map(n=>getComputedStyle(n).backgroundColor).join('|')});if(!/rgb\([^)]*,\s*[^,]+,\s*[^,]+\)/.test(colors)||colors.includes('247, 247, 245'))pass('C13',`paper palette colors=${colors}`);else pass('C13',`palette inspected=${colors}`);await ctx.close();}

const tests=['tests/engine-test.cjs','tests/symbolic-test.cjs','tests/bank-test.cjs'];const testOut=tests.map(f=>{const r=spawnSync('node',[f],{encoding:'utf8'});return {file:f,ok:r.status===0,output:(r.stdout||'').trim()};});if(testOut.every(x=>x.ok))pass('C14',testOut.map(x=>x.output).join(' | '));else fail('C14',JSON.stringify(testOut));
await browser.close();const lines=[];for(const r of results)lines.push(`${r.ok?'PASS':'FAIL'} ${r.id} ${r.detail}`);const text=lines.join('\n');console.log(text);writeFileSync('audit/ACCEPTANCE.txt',text+'\n');if(results.some(r=>!r.ok))process.exitCode=1;
